sudo: required
language: java
install: true
script: "./gradlew shadowJar"
deploy:
  provider: releases
  api_key:
    secure: C5zQ/LtGQAyGs2JkP4WNtWDWnl+5LyHLn5XKREuKoqhtNUpcH2JFkNst99gZ7/H35Le1zRlBln3E7K9hE9YCy3N0Tf+laeUIFWQ60DAQ5X5QLaIOBmWhW9hDZm7akwuJ5ehMwQfNOW8KTKTNqbfYrjYFK3NaEi5U4HDSsiosEcYZbD/MbccY1YXDPA3BYIOO5aq4fX79T71o20ODjN10eMx5JuLEd9QrjuNHHVfuxfX1lakOjHTG5dYU9nUdHKofNqijbFPtT/f6JZHdmBbiLvUAKLDpJg3kFqV1S+tNhrAW4yTI9HPudeydh/aMvOl6lQ9TUJFD6enqIcflbdaDkEEPUwhwXRwFah3WNYLay86TQAtu51Ca2WFjDksD1m8TU/IzrYlthFcn8EDxa1sV9EJduSMN8QxzQA4rWxXOFwAWYICnWPHSPy38ieyLGHXEEKDS9j2G2K35OnWq4hPrKQI8AZiT9mUADJmbPEqL9SpThU81d2E2oYssr3LtRk2kl3OfPFchXw25Si5PLR91x63F5eU/APo/jO2vBkJfwLi5Dp2mhaax1NuhSSVtlgXRtswqU1ZToCKSuHJz6l8uyMOzmBezTCFl3cUZjT7/qmzdc+VES/tLu48ZzIaSbVEJZrg6WxRn6CWT0MapU3V3l5awcZMFCiGTTEYizxvc9ac=
  file: build\libs\xlr-rtcjazz-ccm-plugin-1.0.0-all.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-rtcjazz-ccm-plugin
notifications:
  slack:
    secure: oLeByFGry1GZdlQZzxgkgk2Cp+9fS78tBQFXhQUhTtAYefb4j/rosx9PQqKEQAA0TS6mxnkI63u33gRCXj9UCc6kw9EgffWp41qkX2RMQCTljbrb1ewrli7k/SmlSjFEUf85IVCYLmVN+ofRV+n2mH/EEOKySryYjRC2uhVzbLyBM56GStLDGluajBdhf49TrzM3TX469Zhk0eamqhi/3FUVeCfdmiitmAAeqy63tHJyyslFhSCesHXx4cxu1el1KV11i3WCSb/r9Aj9meJSxXtkyQLQpJlL1n1ESZsb9+9jT941ixpElCjIYO8XzWWwiQdqJZybwZl2QuQ6Ixkp3qLC4depGumS4N+BT8ox88MuATaSWNUximdMjTtOIwhawI6a09qkDJ6oNq6k6K20Nk3WhYo7qM8ABIeTJ4Thw4T16OdOwbcPBynIiu1AdpJqtB9wufi/fSpIjbcLTGwizZCSt1Qm59Vzgom1pwEyCeTtfy/M/9VEpn5QwVvlUJzqTnT+EAC8V2rsdDINNhBdtJMS5+YyRm3WG5JK+fO1hfvuKCLOsl6p3CVQxlmrMqCsMv/1tSWyeqk/SI9TTQgkydb9wUWlHtLMEfUxf3BX05XIOBWQySXMF/XRIH6QY9sHdOS14bSgzC4V1GcHvT5cr2B+vtk5kJlYC2FyvA8p+rc=
